"""Contracts and building blocks for the STFA sequential attack."""

from .action_factors import (
    HIGHWAY_5_LABELS,
    SUMO_3X3_LABELS,
    ActionFactor,
    ActionFactorization,
    highway_5_factorization,
    sumo_3x3_factorization,
)
from .attack import (
    DefenseAdaptationMode,
    DefenseTransform,
    DiscreteEditPlanner,
    SemanticTemporalFactorizedAttack,
    STFAAttackConfig,
    STFANumericalFailure,
    STFAProjectionFailure,
    STFATimingMode,
)
from .contracts import (
    AttackAccounting,
    AttackStepContext,
    DirectorDecision,
    DiscreteEdit,
    EpisodeContext,
    RNGNamespace,
    SafetyCostCritic,
    SequentialAttackResult,
    TemporalDirector,
    TransitionContext,
)
from .highway import (
    HIGHWAY_META_ACTIONS,
    HighwayActionFactor,
    HighwayProjector,
    HighwayRuntimeDescriptor,
)
from .objective import (
    STFAObjectiveTerms,
    STFAObjectiveVariant,
    STFAObjectiveWeights,
    evaluate_stfa_objective,
)
from .projection import PolicyInputProjector, ProjectionResult, Projector
from .sumo_v1 import (
    SUMO_ACTION_FACTORS,
    SUMO_CONTRACT_VERSION,
    SUMO_DISCRETE_INDICES,
    SUMO_FEATURE_NAMES,
    SUMO_OBSERVATION_DIM,
    SumoActionFactor,
    SumoMergeV1DiscretePlanner,
    SumoMergeV1Projector,
    SumoPhysicalBudgetsV1,
    sumo_action_factor,
)
from .temporal import (
    TemporalBudgetEntry,
    TemporalBudgetLedger,
    TemporalBudgetSnapshot,
    TemporalBudgetSpec,
    TemporalBudgetViolation,
)

__all__ = [
    "HIGHWAY_5_LABELS",
    "SUMO_3X3_LABELS",
    "ActionFactor",
    "ActionFactorization",
    "AttackAccounting",
    "AttackStepContext",
    "DefenseAdaptationMode",
    "DefenseTransform",
    "DirectorDecision",
    "DiscreteEdit",
    "DiscreteEditPlanner",
    "EpisodeContext",
    "HIGHWAY_META_ACTIONS",
    "HighwayActionFactor",
    "HighwayProjector",
    "HighwayRuntimeDescriptor",
    "PolicyInputProjector",
    "ProjectionResult",
    "Projector",
    "RNGNamespace",
    "STFANumericalFailure",
    "STFAObjectiveTerms",
    "STFAObjectiveVariant",
    "STFAObjectiveWeights",
    "STFAProjectionFailure",
    "STFATimingMode",
    "SUMO_ACTION_FACTORS",
    "SUMO_CONTRACT_VERSION",
    "SUMO_DISCRETE_INDICES",
    "SUMO_FEATURE_NAMES",
    "SUMO_OBSERVATION_DIM",
    "SafetyCostCritic",
    "SequentialAttackResult",
    "STFAAttackConfig",
    "SemanticTemporalFactorizedAttack",
    "SumoActionFactor",
    "SumoMergeV1DiscretePlanner",
    "SumoMergeV1Projector",
    "SumoPhysicalBudgetsV1",
    "TemporalBudgetEntry",
    "TemporalBudgetLedger",
    "TemporalBudgetSnapshot",
    "TemporalBudgetSpec",
    "TemporalBudgetViolation",
    "TemporalDirector",
    "TransitionContext",
    "evaluate_stfa_objective",
    "highway_5_factorization",
    "sumo_action_factor",
    "sumo_3x3_factorization",
]
