"""Projection contracts for semantic, policy-input observation attacks.

The projectors in this package operate on the *exact array consumed by the
policy*.  They do not mutate simulator state and therefore must not be
described as enforcing physical realizability.  Environment-specific
projectors may add schema constraints, while :class:`PolicyInputProjector`
provides the shared numerical envelope.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

import numpy as np
from numpy.typing import ArrayLike, NDArray

from rl_attack.attacks.strong.stfa.contracts import DiscreteEdit

FloatArray = NDArray[np.float32]


@dataclass(frozen=True)
class ProjectionResult:
    """One projected policy input and auditable projection accounting.

    ``schema_consistent`` only asserts the constraints implemented by the
    selected projector.  In particular, it is not evidence that the projected
    observation can be generated by a physical simulator state.
    """

    clean_observation: FloatArray
    observation: FloatArray
    perturbation: FloatArray
    schema_consistent: bool
    continuous_linf: float
    continuous_l2: float
    discrete_cost: int = 0
    applied_edits: tuple[DiscreteEdit, ...] = ()
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        clean = np.asarray(self.clean_observation, dtype=np.float32)
        observation = np.asarray(self.observation, dtype=np.float32)
        perturbation = np.asarray(self.perturbation, dtype=np.float32)
        if not clean.shape or observation.shape != clean.shape:
            raise ValueError(
                "projection clean and projected observations must share a non-empty shape"
            )
        if perturbation.shape != clean.shape:
            raise ValueError("projection perturbation shape must match the observation")
        if not (
            np.isfinite(clean).all()
            and np.isfinite(observation).all()
            and np.isfinite(perturbation).all()
        ):
            raise ValueError("projection arrays must contain only finite values")
        actual_perturbation = (observation - clean).astype(np.float32, copy=False)
        if not np.array_equal(perturbation, actual_perturbation):
            raise ValueError(
                "projection perturbation must equal observation-clean_observation"
            )
        if type(self.schema_consistent) is not bool:
            raise TypeError("schema_consistent must be bool")

        edits = tuple(self.applied_edits)
        if any(not isinstance(edit, DiscreteEdit) for edit in edits):
            raise TypeError("applied_edits must contain only DiscreteEdit values")
        indices = [edit.feature_index for edit in edits]
        if len(set(indices)) != len(indices):
            raise ValueError("each projected discrete feature may be edited at most once")
        flat_clean = clean.reshape(-1)
        flat_observation = observation.reshape(-1)
        for edit in edits:
            if edit.feature_index >= flat_clean.size:
                raise ValueError("projected discrete edit index is outside the observation")
            if not np.isclose(
                flat_clean[edit.feature_index],
                edit.before,
                rtol=0.0,
                atol=2.0e-7,
            ) or not np.isclose(
                flat_observation[edit.feature_index],
                edit.after,
                rtol=0.0,
                atol=2.0e-7,
            ):
                raise ValueError(
                    "projected discrete edit values do not match the observation pair"
                )
        expected_discrete_cost = sum(edit.cost for edit in edits)
        if (
            isinstance(self.discrete_cost, bool)
            or not isinstance(self.discrete_cost, int)
            or self.discrete_cost != expected_discrete_cost
        ):
            raise ValueError(
                "projection discrete_cost must equal the sum of applied edit costs"
            )

        continuous_mask = np.ones(flat_clean.size, dtype=np.bool_)
        if indices:
            continuous_mask[indices] = False
        continuous = actual_perturbation.reshape(-1)[continuous_mask]
        expected_linf = (
            float(np.max(np.abs(continuous))) if continuous.size else 0.0
        )
        expected_l2 = float(
            np.linalg.norm(continuous.astype(np.float64, copy=False), ord=2)
        )
        for name, declared, expected in (
            ("continuous_linf", self.continuous_linf, expected_linf),
            ("continuous_l2", self.continuous_l2, expected_l2),
        ):
            if (
                isinstance(declared, bool)
                or not isinstance(declared, (int, float, np.integer, np.floating))
                or not np.isfinite(float(declared))
                or float(declared) < 0.0
                or not np.isclose(
                    float(declared), expected, rtol=1.0e-6, atol=1.0e-8
                )
            ):
                raise ValueError(f"projection {name} is inconsistent with its arrays")
        if not isinstance(self.metadata, Mapping):
            raise TypeError("projection metadata must be a mapping")

        clean = clean.copy()
        observation = observation.copy()
        perturbation = perturbation.copy()
        clean.setflags(write=False)
        observation.setflags(write=False)
        perturbation.setflags(write=False)
        object.__setattr__(self, "clean_observation", clean)
        object.__setattr__(self, "observation", observation)
        object.__setattr__(self, "perturbation", perturbation)
        object.__setattr__(self, "continuous_linf", expected_linf)
        object.__setattr__(self, "continuous_l2", expected_l2)
        object.__setattr__(self, "applied_edits", edits)
        object.__setattr__(self, "metadata", dict(self.metadata))

    @property
    def projected_observation(self) -> FloatArray:
        """Compatibility alias that makes the result meaning explicit."""

        return self.observation


@runtime_checkable
class Projector(Protocol):
    """Protocol shared by generic and environment-semantic projectors."""

    @property
    def observation_shape(self) -> tuple[int, ...]:
        ...

    def project(
        self,
        clean_observation: ArrayLike,
        candidate_observation: ArrayLike,
        *,
        discrete_edits: Sequence[DiscreteEdit] = (),
    ) -> ProjectionResult:
        """Project a candidate observation into the declared threat set."""


def _shape_tuple(shape: Sequence[int]) -> tuple[int, ...]:
    result = tuple(int(value) for value in shape)
    if not result or any(value <= 0 for value in result):
        raise ValueError("observation_shape must contain positive dimensions")
    return result


def _exact_feature_array(
    value: ArrayLike,
    *,
    shape: tuple[int, ...],
    name: str,
    dtype: np.dtype[Any],
    allow_scalar: bool,
) -> np.ndarray:
    array = np.asarray(value, dtype=dtype)
    if array.shape == () and allow_scalar:
        return np.full(shape, array.item(), dtype=dtype)
    if array.shape != shape:
        expected = "a scalar or " if allow_scalar else ""
        raise ValueError(f"{name} must be {expected}have exact shape {shape}")
    return array.copy()


class PolicyInputProjector:
    """Exact L-infinity, mask, bounds, and finiteness projection.

    Inputs are single policy observations rather than implicit batches.
    Feature constraints may be scalars or exact-shape arrays; NumPy's more
    permissive broadcasting is intentionally rejected to prevent a budget
    being applied to the wrong axis.
    """

    def __init__(
        self,
        *,
        observation_shape: Sequence[int],
        epsilon: ArrayLike,
        lower: ArrayLike,
        upper: ArrayLike,
        mutable_mask: ArrayLike,
        name: str = "policy_input_linf",
    ) -> None:
        self._observation_shape = _shape_tuple(observation_shape)
        self.name = str(name).strip()
        if not self.name:
            raise ValueError("projector name cannot be empty")

        self.epsilon = _exact_feature_array(
            epsilon,
            shape=self._observation_shape,
            name="epsilon",
            dtype=np.dtype(np.float32),
            allow_scalar=True,
        )
        self.lower = _exact_feature_array(
            lower,
            shape=self._observation_shape,
            name="lower",
            dtype=np.dtype(np.float32),
            allow_scalar=True,
        )
        self.upper = _exact_feature_array(
            upper,
            shape=self._observation_shape,
            name="upper",
            dtype=np.dtype(np.float32),
            allow_scalar=True,
        )
        self.mutable_mask = _exact_feature_array(
            mutable_mask,
            shape=self._observation_shape,
            name="mutable_mask",
            dtype=np.dtype(np.bool_),
            allow_scalar=True,
        )
        if not np.isfinite(self.epsilon).all() or np.any(self.epsilon < 0.0):
            raise ValueError("epsilon must be finite and non-negative")
        if np.isnan(self.lower).any() or np.isnan(self.upper).any():
            raise ValueError("lower and upper bounds cannot contain NaN")
        if np.any(self.lower > self.upper):
            raise ValueError("lower bounds cannot exceed upper bounds")

        # A zero budget is immutable even if the caller accidentally marks it
        # mutable.  Expose the effective mask so accounting and tests agree.
        self.mutable_mask = np.logical_and(self.mutable_mask, self.epsilon > 0.0)

    @property
    def observation_shape(self) -> tuple[int, ...]:
        return self._observation_shape

    def _observation(self, value: ArrayLike, *, name: str) -> FloatArray:
        try:
            array = np.asarray(value, dtype=np.float32)
        except (TypeError, ValueError) as error:
            raise ValueError(f"{name} must be a numeric observation") from error
        if array.shape != self.observation_shape:
            raise ValueError(
                f"{name} must have exact policy-input shape {self.observation_shape}; "
                f"got {array.shape}"
            )
        if not np.isfinite(array).all():
            raise ValueError(f"{name} must contain only finite values")
        return array.copy()

    def _continuous_projection(
        self,
        clean_observation: ArrayLike,
        candidate_observation: ArrayLike,
        *,
        mutable_mask: NDArray[np.bool_] | None = None,
    ) -> tuple[FloatArray, dict[str, int]]:
        clean = self._observation(clean_observation, name="clean_observation")
        candidate = self._observation(
            candidate_observation,
            name="candidate_observation",
        )
        tolerance = 8.0 * np.finfo(np.float32).eps
        if np.any(clean < self.lower - tolerance) or np.any(
            clean > self.upper + tolerance
        ):
            raise ValueError("clean_observation lies outside declared validity bounds")

        effective_mask = self.mutable_mask
        if mutable_mask is not None:
            extra_mask = np.asarray(mutable_mask, dtype=np.bool_)
            if extra_mask.shape != self.observation_shape:
                raise ValueError(
                    "runtime mutable_mask must have exact policy-input shape "
                    f"{self.observation_shape}"
                )
            effective_mask = np.logical_and(effective_mask, extra_mask)

        delta = candidate - clean
        budget_delta = np.clip(delta, -self.epsilon, self.epsilon)
        budget_delta = np.where(effective_mask, budget_delta, np.float32(0.0))
        projected = clean + budget_delta
        bounded = np.clip(projected, self.lower, self.upper)
        bounded = np.where(effective_mask, bounded, clean).astype(np.float32, copy=False)
        if not np.isfinite(bounded).all():
            raise RuntimeError("projection produced a non-finite policy input")

        budget_clipped = int(
            np.count_nonzero(
                effective_mask
                & ~np.isclose(
                    delta,
                    budget_delta,
                    rtol=0.0,
                    atol=np.finfo(np.float32).eps,
                )
            )
        )
        bounds_clipped = int(
            np.count_nonzero(
                effective_mask
                & ~np.isclose(
                    projected,
                    bounded,
                    rtol=0.0,
                    atol=np.finfo(np.float32).eps,
                )
            )
        )
        immutable_restored = int(
            np.count_nonzero(
                ~effective_mask
                & ~np.isclose(
                    candidate,
                    clean,
                    rtol=0.0,
                    atol=np.finfo(np.float32).eps,
                )
            )
        )
        return bounded.copy(), {
            "budget_clipped_coordinates": budget_clipped,
            "bounds_clipped_coordinates": bounds_clipped,
            "immutable_restored_coordinates": immutable_restored,
        }

    @staticmethod
    def _result(
        clean: FloatArray,
        observation: FloatArray,
        *,
        schema_consistent: bool,
        continuous_mask: ArrayLike | None = None,
        applied_edits: Sequence[DiscreteEdit] = (),
        metadata: Mapping[str, Any] | None = None,
    ) -> ProjectionResult:
        perturbation = (observation - clean).astype(np.float32, copy=False)
        if continuous_mask is None:
            continuous = perturbation
        else:
            mask = np.asarray(continuous_mask, dtype=np.bool_)
            if mask.shape != perturbation.shape:
                raise ValueError(
                    "continuous_mask must have the exact projected observation shape"
                )
            continuous = perturbation[mask]
        flat = continuous.reshape(-1)
        continuous_linf = float(np.max(np.abs(flat))) if flat.size else 0.0
        continuous_l2 = float(np.linalg.norm(flat.astype(np.float64), ord=2))
        edits = tuple(applied_edits)
        discrete_cost = sum(int(edit.cost) for edit in edits)
        return ProjectionResult(
            clean_observation=clean.astype(np.float32, copy=True),
            observation=observation.astype(np.float32, copy=True),
            perturbation=perturbation.copy(),
            schema_consistent=bool(schema_consistent),
            continuous_linf=continuous_linf,
            continuous_l2=continuous_l2,
            discrete_cost=int(discrete_cost),
            applied_edits=edits,
            metadata={} if metadata is None else dict(metadata),
        )

    def project(
        self,
        clean_observation: ArrayLike,
        candidate_observation: ArrayLike,
        *,
        discrete_edits: Sequence[DiscreteEdit] = (),
    ) -> ProjectionResult:
        if discrete_edits:
            raise ValueError(
                "PolicyInputProjector cannot apply semantic discrete edits; "
                "use an environment-specific projector"
            )
        clean = self._observation(clean_observation, name="clean_observation")
        projected, accounting = self._continuous_projection(clean, candidate_observation)
        return self._result(
            clean,
            projected,
            schema_consistent=True,
            metadata={
                "projector": self.name,
                "guarantee": "policy_input_constraints_only",
                **accounting,
            },
        )


__all__ = [
    "PolicyInputProjector",
    "ProjectionResult",
    "Projector",
]
