"""Public, implementation-level APIs for the native P5 RAPID-Guard defense.

Stable-Baselines3 construction lives in :mod:`rl_attack.defenses.rapid_guard.sb3`
because that adapter also depends on the training bundle package.
"""

from .calibration import (
    CleanCalibrationCohort,
    RapidGuardArtifact,
    calibrate_split_conformal,
    finite_sample_order_index,
)
from .contracts import (
    CERTIFICATE_SCOPE,
    DETECTOR_CHANNELS,
    NON_CERTIFIED_CLAIMS,
    DetectorChannels,
    RapidGuardBinding,
    SplitSeedRegistry,
)
from .denoiser import (
    PROPOSAL_GUARANTEE_SCOPE,
    FrozenResidualDenoiser,
    ResidualDenoiser,
    ResidualDenoiserBatch,
    ResidualDenoiserConfig,
    ResidualDenoiserTrainConfig,
    ResidualDenoiserTrainingResult,
    train_residual_denoiser,
)
from .detector import (
    FrozenLogisticRiskHead,
    FusionFitCohort,
    FusionFitConfig,
    FusionTrainingResult,
    IBPMarginDeficit,
    categorical_js_divergence,
    evaluate_detector_channels,
    fit_attack_exposed_fusion,
    ibp_greedy_action_margin_deficit,
    temporal_innovation_score,
)
from .fallback import (
    ActionWiseSafetyCostCritic,
    FallbackDecision,
    SafetyCostFallback,
    StaticFallbackConfig,
)
from .guard import (
    ActionInvarianceCertificate,
    ActionInvarianceCertifier,
    AdaptiveDefenseDeclaration,
    BPDAIdentityPurifierAdapter,
    CategoricalPolicyProtocol,
    CertificateMode,
    DetectionAssessment,
    DetectorProtocol,
    GuardCostProxies,
    GuardEpisodeAccounting,
    GuardPath,
    GuardStepAccounting,
    GuardStepResult,
    RapidGuard,
    SafetyShieldProtocol,
    ShieldDecision,
    WhiteBoxAdaptiveDefenseAdapter,
)
from .purifier import (
    POLICY_INPUT_GUARANTEE,
    FrozenProposalTransform,
    FrozenSemanticProjector,
    PurificationCandidate,
    PurificationFailure,
    PurificationPlan,
    PurifierConfig,
    SemanticTemporalPurifier,
)

__all__ = [
    "CERTIFICATE_SCOPE",
    "DETECTOR_CHANNELS",
    "NON_CERTIFIED_CLAIMS",
    "POLICY_INPUT_GUARANTEE",
    "PROPOSAL_GUARANTEE_SCOPE",
    "ActionInvarianceCertificate",
    "ActionInvarianceCertifier",
    "ActionWiseSafetyCostCritic",
    "AdaptiveDefenseDeclaration",
    "BPDAIdentityPurifierAdapter",
    "CategoricalPolicyProtocol",
    "CertificateMode",
    "CleanCalibrationCohort",
    "DetectionAssessment",
    "DetectorChannels",
    "DetectorProtocol",
    "FallbackDecision",
    "FrozenLogisticRiskHead",
    "FrozenProposalTransform",
    "FrozenResidualDenoiser",
    "FrozenSemanticProjector",
    "FusionFitCohort",
    "FusionFitConfig",
    "FusionTrainingResult",
    "GuardCostProxies",
    "GuardEpisodeAccounting",
    "GuardPath",
    "GuardStepAccounting",
    "GuardStepResult",
    "IBPMarginDeficit",
    "PurificationCandidate",
    "PurificationFailure",
    "PurificationPlan",
    "PurifierConfig",
    "RapidGuard",
    "RapidGuardArtifact",
    "RapidGuardBinding",
    "ResidualDenoiser",
    "ResidualDenoiserBatch",
    "ResidualDenoiserConfig",
    "ResidualDenoiserTrainConfig",
    "ResidualDenoiserTrainingResult",
    "SafetyCostFallback",
    "SafetyShieldProtocol",
    "SemanticTemporalPurifier",
    "ShieldDecision",
    "SplitSeedRegistry",
    "StaticFallbackConfig",
    "WhiteBoxAdaptiveDefenseAdapter",
    "calibrate_split_conformal",
    "categorical_js_divergence",
    "evaluate_detector_channels",
    "finite_sample_order_index",
    "fit_attack_exposed_fusion",
    "ibp_greedy_action_margin_deficit",
    "temporal_innovation_score",
    "train_residual_denoiser",
]
